config/routes.rb
Rails.application.routes.draw do
  get "home/index"

  resources :docs
  authenticated :user do
    root 'docs#index', as: :authenticated_root
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: %i[ show edit update destroy ]

  # GET /docs or /docs.json
  def index
    @docs = Doc.where(user_id: current_user).all.order(created_at: :desc)
  end

  # GET /docs/1 or /docs/1.json
  def show
  end

  # GET /docs/new
  def new
    @doc = current_user.docs.new
  end

  # GET /docs/1/edit
  def edit
  end

  # POST /docs or /docs.json
  def create
    @doc = current_user.docs.new(doc_params)

    respond_to do |format|
      if @doc.save
        format.html { redirect_to doc_url(@doc), notice: "Doc was successfully created." }
        format.json { render :show, status: :created, location: @doc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docs/1 or /docs/1.json
  def update
    respond_to do |format|
      if @doc.update(doc_params)
        format.html { redirect_to doc_url(@doc), notice: "Doc was successfully updated." }
        format.json { render :show, status: :ok, location: @doc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1 or /docs/1.json
  def destroy
    @doc.destroy!

    respond_to do |format|
      format.html { redirect_to docs_url, notice: "Doc was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doc
      @doc = Doc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/docs/_doc.html.erb
<div id="<%= dom_id doc %>">
  <p>
    <strong>Title:</strong>
    <%= doc.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= doc.content %>
  </p>

</div>

app/views/docs/_form.html.erb
<%= simple_form_for(@doc) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<% content_for :title, "Editing doc" %>

<h1>Editing doc</h1>

<%= render "form", doc: @doc %>

<br>

<div>
  <%= link_to "Show this doc", @doc %> |
  <%= link_to "Back to docs", docs_path %>
</div>

app/views/docs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Docs" %>

<h1>Docs</h1>

<div id="docs">
  <% @docs.each do |doc| %>
    <%= render doc %>
    <p>
      <%= link_to "Show this doc", doc %>
    </p>
  <% end %>
</div>

<%= link_to "New doc", new_doc_path %>

app/views/docs/new.html.erb
<% content_for :title, "New doc" %>

<h1>New doc</h1>

<%= render "form", doc: @doc %>

<br>

<div>
  <%= link_to "Back to docs", docs_path %>
</div>

app/views/docs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @doc %>

<div>
  <%= link_to "Edit this doc", edit_doc_path(@doc) %> |
  <%= link_to "Back to docs", docs_path %>

  <%= button_to "Destroy this doc", @doc, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cabinet" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render 'shared/navbar' %>
  <div class='container'>
    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>
    <%= yield %>
  </div>

  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top bg-body-tertiary bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">My Documents</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link #{'active' if current_page?(root_path)}", aria: { current: "page" } %>
        </li>
        <li class="nav-item">
          <%= link_to "Documents", docs_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Document", new_doc_path, class: "nav-link" %>
        </li>
    </div>
        <li class="nav-item justify-content-end">
          <% if current_user %>
            <li class="nav-item d-flex flex-column">
              <strong class="text-white"><%= current_user.email %></strong>
              <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, method: :delete, style: "text-decoration: none;" %>
            </li>
          <% else %>
            <li class="nav-item d-flex flex-column">
              <%= link_to 'Sign in', new_user_session_path, class: "text-decoration-none" %>
              <%= link_to 'Sign up', new_user_registration_path, class: "text-decoration-none" %>
            </li>
          <% end %>
        </li>
      </ul>
  </div>
</nav>